# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rsswift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rsswift
  pod 'Google-Mobile-Ads-SDK', '~> 7.9.1'
  pod 'ReachabilitySwift', '~> 4.1.0'
  pod 'Toast-Swift', '~> 2.0.0'
  #pod 'Google-Mobile-Ads-SDK'

end
